#3 Added check for correct number of command-line arguments
kimlew/python-rename-files pull request #4
Opened 2019-07-02 19:13 UTC by kimlew

Resolved #3
@kcharter As Lola suggested, I've added a check for the correct number of command-line arguments in get_input().

2019-07-03 06:03 UTC, kcharter requested changes
Thinking about it, it's probably better to adopt the 'Pythonic' practice of raising an exception in `get_input`.

2019-07-03 06:03 UTC, kcharter commented on rename_files.py
>      print()
You've changed these three lines with the print statements in different ways in your two PRs. Obviously the changes aren't a big deal but in general it's a good idea to keep a PR focused on a single purpose, where all the changes contribute to that purpose.

No need to change anything here, just wanted to point it out.

2019-07-03 06:03 UTC, kcharter commented on rename_files.py
> +
This works but it has the drawback that a decision to exit the program is buried in a function, and most people advise putting that kind of thing in the main block.

To do that, you'd change your check to raise an exception with a nicer error message:

```
if len(sys.argv) != 4:
    raise Exception("Error: Wrong number of arguments ...")
```

If you leave it like that, when the user gives the wrong number of arguments, there will still be a stack trace, but the message will explain the problem in terms that make more sense to the user.

2019-07-04 02:13 UTC, kimlew commented on rename_files.py
>      print()
Ok. Changed it to Pythonic way to handle IndexError.

2019-07-04 02:17 UTC, kcharter approved these changes

2019-07-04 02:18 UTC, merged